### PR TITLE
v2.0 

### PR DESCRIPTION
**Pull request by OmarSainab**
This PR for version 2.0 release includes the following changes:

- Fix of whitespace before or after the variable 'id'.
- CSRF protection on the flask server

- Clusters overlaid markers on maps
- New markers on maps and legends 
- Fix of popup table tabs & movement arrows (cattle movement page only)

- Splitting and updating html and css files
- Async loading of leaflet, cattle movement and SNP script files 
-  Navigation bar bug and UI fixes
- Layout shift fixes on page load

### CODE REVIEW

**Comment by ellisrichardj** [comment]
Looking good 👍 - have these updates been merged into prod-test and checked through the PaloAlto access route (ViewBovis-testing)?

**Comment by Hira-Naveed** [comment]
Looking good well done! I am happy to review in the PaloAlto VB-Testing port by using this checklist: https://defra.sharepoint.com/:w:/r/teams/Team4008/_layouts/15/Doc.aspx?sourcedoc=%7BFA3F5A41-F72D-4518-AAB1-FF02AE5A2D26%7D&file=ViewBovisChecks_FollowingARelease_September2023.docx&action=default&mobileredirect=true , I have tried to access the testing port but nothing is there yet - maybe this has been checked already @praveenmurugan101

**Comment by OmarSainab** [comment]
> Looking good 👍 - have these updates been merged into prod-test and checked through the PaloAlto access route (ViewBovis-testing)?

Yes, the updates have been merged into prod-test. Viewbovis-test has now been deployed and going through [checks ](https://defra.sharepoint.com/:w:/r/teams/Team4008/_layouts/15/Doc.aspx?sourcedoc=%7BFA3F5A41-F72D-4518-AAB1-FF02AE5A2D26%7D&file=ViewBovisChecks_FollowingARelease_September2023.docx&action=default&mobileredirect=true)  👍

**Review by ellisrichardj — APPROVED** [review]
This is looking great - some fantastic improvements for our users.  Good work team 💯

**Pull request merged**
