### PR TITLE
Security Vulnerabilities fixes for dependencies

### PR DESCRIPTION
**Pull request by praveenmurugan101**
- npm audit fixes
- css-select updates to latest version
- nth-check version overrides to stable version
- flask updates to stable version
- gunicorn updates to latest version
-  other dependencies updates to stable version in requirement.txt
-  manifest file error fixes
-  lazy loads nextstrain to increase performance

### CODE REVIEW

**Review by ellisrichardj — APPROVED** [review]
Great to get these vulnerabilities fixed 👍

**Review by sainab-omar — APPROVED** [review]
Great fixes, well done 👍

**Review by televisedbrain — APPROVED** [review]

**Review by sainab-omar — APPROVED** [review]
Looks good 👍

**Review by ellisrichardj — APPROVED** [review]
Good work again!

**Pull request merged**
